### ISSUE TITLE
Juno Nozzle V5

### ISSUE THREAD

**Issue by phoem** [OUTOFDARTSSHOP/Rival-Juno-Blaster#1]
Hey, The juno nozzle v5 either is not the latest version (only has 1 screw) or the directions need to be updated (shows a two screw version).  Not critical just feels like it was changed to add a two screw version but that may not have been uploaded yet.  Btw love the project and love the directions and the updates.  Thank you for all your hard work.

**Comment by Turokhunter** [comment]
It’s both. The nozzle is held by one screw. The other screw holds the hop-up tab. It was designed so people can pick different hop-up tabs depending on the motors used.  The manual needs to be updated to show that. If you look at the 3rd print orientation image other manual you can see the tiny hopup between the trigger and rails. You can also gain slightly better performance if it’s printed TPU. All things that aren’t mentioned in the manual. 

Thank you for pointing out that something was wrong. I can’t tell you how hard it’s to catch all these tiny mistakes. I appreciate you taking the time to reach out.

**Comment by phoem** [comment]
No problem, trust me I know I do software programming for a living, its impossible to find everything then combine that with having documentation you are maintaining too, it can't be easy.  Thanks for taking the time to explain what I wasn't seeing.

**Comment by phoem** [comment]
Btw I am happy to help test anything before you release to main,whatever I can do to help

**Comment by Turokhunter** [comment]
I appreciate the offer. In the other issue, I posted two pusher wheels you can try to fit off. I also do software development for a living. Once we get those tested, I will update the manual and the STL files.

Thanks for the help.

**Comment by Turokhunter** [comment]
Updated in 5.3
