### ISSUE TITLE
N20 pusher wheel doesn't fit

### ISSUE THREAD

**Issue by phoem** [OUTOFDARTSSHOP/Rival-Juno-Blaster#2]
I have tried printing both v5 and v5.1 of the pusher wheel and I can't get it to fit on the n20.  I have tried reaming out the hole but then it ends up too loose.  Printing on an X1C that is tuned and accurate.  I suspect this piece may need a few different versions or setting's depending on the printers accuracy but everything else in the build fits like a glove.  Thanks again for your hard work.

**Comment by Turokhunter** [comment]
I expected this to happen. Give these two a try and let me know: https://www.dropbox.com/scl/fi/wcts8ksx3dfdsa4wa2cmc/Juno-Pusher-Loose_V5.2.stl?rlkey=7y8zn0qvalkjomlh7curmctxz&dl=0
https://www.dropbox.com/scl/fi/cj68pm7o5jzgaby5kloid/Juno-Pusher-VeryLoose_V5.2.stl?rlkey=sqlzrwozlnpd9nxylor6hnr6j&dl=0

**Comment by KookyMawnster** [comment]
V5.1 worked for me Ender 2 Pro "hole horizontal expansion" = 0.1mm

**Comment by phoem** [comment]
The loose version fits great, slides right on.  Very loose still fits of course but slides right off.

Thanks for the help.  Let me know if you want me to send photos

**Comment by Turokhunter** [comment]
New files can be found in 5.3 version.
